title: Hello, world! I'm Maryam Ghaseri
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Maryam Ghaseri # add your name
author-img: Maryam-Ghaseri.jpg # add your photo
about-author: I am a data scentist and an actuary. Always hungry to keep learning. # add description
social-github: maryam4420 # add your Github handle
social-linkedin: https://www.linkedin.com/in/maryam-ghaseri-asa-maaa-5017ba58/
social-email: maryam.ghaserin@gmail.com

# Disqus
discus-identifier: maryam-ghaseri # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
